name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repo
        uses: actions/checkout@v3
        with:
          path: test-repo

      - name: Checkout API repo
        uses: actions/checkout@v3
        with:
          repository: wooyeoup-rho/python-projects
          path: api-repo

#      - name: Install docker-compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose version

      - name: Create docker-compose for CI
        working-directory: test-repo/cafe-api-tests
        run: |
          cat > docker-compose.ci.yml << 'EOF'
          services:
            api:
              build:
                context: ../../../api-repo/flask/cafe-api
              container_name: cafe_api
              ports:
                - "5000:5000"
              environment:
                - FLASK_ENV=development
              healthcheck:
                test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/all', timeout=2).read()"]
                interval: 3s
                timeout: 3s
                retries: 20
                start_period: 10s

            newman:
              image: postman/newman:latest
              container_name: cafe_tests
              depends_on:
                api:
                  condition: service_healthy
              volumes:
                - .:/etc/newman
              working_dir: /etc/newman
              entrypoint: /bin/sh
              command:
                - -c
                - |
                  sleep 3
                  newman run cafe-api.json -e cafe-api_env.postman_environment.json -d cafe_data.json --delay-request 1000 --bail
          EOF

      - name: Run tests
        working-directory: test-repo/cafe-api-tests
        run: docker compose -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from newman

      - name: Show test results
        if: always()
        working-directory: test-repo/cafe-api-tests
        run: docker compose -f docker-compose.ci.yml logs newman

      - name: Cleanup
        if: always()
        working-directory: test-repo/cafe-api-tests
        run: docker compose -f docker-compose.ci.yml down